import tkinter as tk

window=tk.Tk()
window.geometry('700x700')
window.resizable(False,False)

colour1='#020f12'
colour2='#05d7ff'
colour3='#65e7ff'
colour4='BLACK'

main_frame=tk.Frame(window,bg=colour1,pady=40)
main_frame.pack(fill=tk.BOTH,expand=True)
main_frame.columnconfigure(0,weight=1)
main_frame.rowconfigure(0,weight=1)
main_frame.rowconfigure(1,weight=1)

Play_button=tk.Button(
    main_frame,
    background=colour2,
    foreground=colour4,
    activebackground=colour3,
    activeforeground=colour4,
    highlightthickness=2,
    highlightbackground=colour3,
    highlightcolor='WHITE',
    width=13,
    height=2,
    border=0,
    cursor='hand1',
    text='Play',
    font=('ARIAL',20),
    )
Quit_button=tk.Button(
    main_frame,
    background='RED',
    foreground=colour4,
    activebackground=colour3,
    activeforeground=colour4,
    highlightthickness=2,
    highlightbackground=colour3,
    highlightcolor='WHITE',
    width=13,
    height=2,
    border=0,
    cursor='hand1',
    text='Quit',
    font=('ARIAL',20),
    )

Settings_button=tk.Button(
    main_frame,
    background=colour2,
    foreground=colour4,
    activebackground=colour3,
    activeforeground=colour4,
    highlightthickness=2,
    highlightbackground=colour3,
    highlightcolor='WHITE',
    width=13,
    height=2,
    border=0,
    cursor='hand1',
    text='Settings',
    font=('ARIAL',20),
    )
Play_button.grid(column=0,row=0)
Settings_button.grid(column=0,row=1)
Quit_button.grid(column=0,row=2)
window.mainloop()